AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: Template to deploy the resources for a demo of Custom Resources

Parameters:
  FirehoseDeliveryArn:
    Description: The ARN of the Firehose delivery stream to update
    Type: String
  FireshoseDeliveryStreamName:
    Description: The name of the Firehose delivery stream to update
    Type: String
  GlueTableName:
    Description: The name of the Glue catalog containing the input schema to be transformed
    Type: String
  GlueDatabaseName:
    Description: The name of the Glue database containig the required table catalogs
    Type: String
  GlueInteractionRole:
    Description: The ARN of a role that allows the Glue DB and table to be read
    Type: String

Resources:
  
  AddRecordConversion:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      CurrentAccountId: !Ref AWS::AccountId
      FirehoseDeliveryStreamName: !Ref FireshoseDeliveryStreamName
      GlueInteractionRole: !Ref GlueInteractionRole
      InputGlueDatabaseName: !Ref GlueDatabaseName
      InputGlueTable: !Ref GlueTableName
      ServiceToken: !GetAtt AddRecordConversionLambda.Arn
      loglevel: debug
    
  AddRecordConversionLambda:
    Type: AWS::Serverless::Function
    DependsOn: LambdaChangeFirehoseRolePolicy
    Properties:
      CodeUri: ./lambdas/custom-add-rec-conv/
      Description: A lambda function backing a custom resource that adds a data convertor to a firehose stream
      Handler: index.lambda_handler
      MemorySize: 128
      Role: !GetAtt LambdaChangeFirehoseRole.Arn
      Runtime: python3.6
      Timeout: 180

  LambdaChangeFirehoseRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
      RoleName: !Sub ${AWS::StackName}-Lambda-Chg-Fh-Role

  LambdaChangeFirehoseRolePolicy:
    Type: AWS::IAM::Policy
    DependsOn: LambdaChangeFirehoseRole
    Properties:
      PolicyDocument:
        Statement:
        - Action: firehose:*
          Effect: Allow
          Resource: !Ref FirehoseDeliveryArn
        - Action: logs:*
          Effect: Allow
          Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*:*
        - Action: iam:PassRole
          Effect: Allow
          Resource: !Ref GlueInteractionRole
      PolicyName: !Sub ${AWS::StackName}-Lambda-Chg-Fh-Policy
      Roles: 
        - !Ref LambdaChangeFirehoseRole

