AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    Copies the built pytz and panda libraries as a lambda layer

Resources:

  PandaLibraryLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: python-panda-library
      Description: Panda data library that can be used by any python 3.7 lambdas
      ContentUri: panda-layer
      CompatibleRuntimes:
        - python3.7
      LicenseInfo: 'MIT'
      RetentionPolicy: Retain

Outputs:
  PandaLibraryLayerArn:
    Description: The ARN of the Lambda layer containing the panda library
    Value: !Ref PandaLibraryLayer